# Generated by Django 4.2.1 on 2023-06-04 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('tipo_contacto', models.IntegerField(choices=[(0, 'Sugerencia'), (1, 'Reclamo'), (2, 'Felicitaciones')])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
