# Generated by Django 4.2.1 on 2023-06-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estilo', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='artistas')),
            ],
        ),
    ]
