# Generated by Django 4.2.1 on 2023-06-23 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0002_artista'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreObra', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('medidas', models.CharField(max_length=20)),
                ('tecnica', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('estado', models.IntegerField(choices=[(0, 'Disponible'), (1, 'Vendida'), (2, 'En Exhibición')])),
                ('imagenObra', models.ImageField(blank=True, null=True, upload_to=None)),
                ('historia', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_contacto',
            field=models.IntegerField(choices=[(0, 'Creado'), (1, 'Aprobado'), (2, 'Rechazado')]),
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreObra', models.CharField(max_length=50)),
                ('medidas', models.CharField(max_length=20)),
                ('tecnica', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('estado', models.IntegerField(choices=[(0, 'Disponible'), (1, 'Vendida'), (2, 'En Exhibición')])),
                ('imagenObra', models.ImageField(blank=True, null=True, upload_to=None)),
                ('historia', models.TextField(null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appweb.artista')),
            ],
        ),
    ]
