# Generated by Django 4.2.2 on 2023-06-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_formularioart_alter_contacto_tipo_contacto_obra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_contacto',
            field=models.IntegerField(choices=[(0, 'Sugerencia'), (1, 'Reclamo'), (2, 'Felicitaciones')]),
        ),
        migrations.AlterField(
            model_name='formularioart',
            name='imagenObra',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obra',
            name='historia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='imagenObra',
            field=models.ImageField(upload_to=None),
        ),
    ]
