# Generated by Django 4.2.1 on 2023-06-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_alter_contacto_tipo_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioart',
            name='imagenObra',
            field=models.ImageField(upload_to='obras'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='imagenObra',
            field=models.ImageField(upload_to='obras'),
        ),
    ]
