# Generated by Django 4.2.2 on 2023-06-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_alter_formularioart_imagenobra_alter_obra_imagenobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='usuario',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
