# Generated by Django 4.2.2 on 2023-06-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0008_artista_correo_alter_formularioart_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='artista',
            name='usuario',
        ),
        migrations.AddField(
            model_name='artista',
            name='contraseña',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artista',
            name='foto_perfil',
            field=models.ImageField(default=None, upload_to='fotos_artista/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artista',
            name='estilo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
