# Generated by Django 4.2.2 on 2023-06-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0009_remove_artista_apellido_remove_artista_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='apellido',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artista',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
