# Generated by Django 4.2.2 on 2023-06-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0010_artista_apellido_alter_artista_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
