# Generated by Django 4.2.2 on 2023-06-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0013_alter_artista_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='apellido',
            field=models.CharField(default='Prueba', max_length=100),
            preserve_default=False,
        ),
    ]
