# Generated by Django 4.2.1 on 2023-06-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0015_alter_artista_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormularioArt',
        ),
    ]
