# Generated by Django 4.2.2 on 2023-06-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0016_delete_formularioart'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='mensaje_rechazo',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
