# Generated by Django 4.2.2 on 2023-06-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0017_obra_mensaje_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='nombreApellido_Autor',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obra',
            name='estado',
            field=models.IntegerField(choices=[(0, 'En Espera de Aprobación'), (1, 'En Exhibición'), (2, 'Rechazado')], default=0),
        ),
    ]
