# Generated by Django 4.2.2 on 2023-06-26 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appweb', '0018_obra_nombreapellido_autor_alter_obra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='Grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='obra',
            name='categoriaObra',
            field=models.IntegerField(choices=[(0, 'Pintura'), (1, 'Escultura'), (2, 'Carpintería')], default=0),
        ),
    ]
