# Generated by Django 4.2.2 on 2023-07-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0019_artista_grupo_obra_categoriaobra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('run', models.CharField(max_length=12)),
                ('foto_perfil', models.ImageField(upload_to='fotos_perfil_postulante/')),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('motivación', models.TextField()),
                ('curriculum', models.FileField(upload_to='curriculums/')),
            ],
        ),
    ]
